### ISSUE TITLE
html: include style.css

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#18]
we need to include [style.css](https://github.com/akshayitzme/cinlist/blob/master/cinlist/static/css/style.css) in the base template

- Target File: [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html) 
- include the css file inside the `<head>` tag, defined in  [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html)
- use `<link href="">` to include a css file.
- ⚠️ please note that, the [style.css](https://github.com/akshayitzme/cinlist/blob/master/cinlist/static/css/style.css) file must be imported after the bootstrap includes.
- ✨ Feel free to ask doubts & add your own changes ! .
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

### Refer:
 [How to load and use static files in Django?](https://www.geeksforgeeks.org/how-to-load-and-use-static-files-in-django/)

### Example:
```html
<head>
...

<link rel="stylesheet" href="{% static 'css/style.css' %}">

...
</head>
```

**Comment by heraldjose10** [comment]
Hi. Can you assign this issue to me?

**Comment by akshayitzme** [comment]
> Hi. Can you assign this issue to me?

sure :+1:  assigning it to you

**Comment by heraldjose10** [comment]
Opened a PR #21 @akshayitzme 
Please take a look.
Let me know if any changes are needed.
