### ISSUE TITLE
py: define attributes for the username field

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#27]
we have to style the username field in the SignUpForm located in [forms.py](https://github.com/akshayitzme/cinlist/blob/master/cinlist/forms.py)

- we can achieve this by adding needed classes and placeholder value in the attrs of the widget variable of the username field.
- Target File: [forms.py](https://github.com/akshayitzme/cinlist-django/blob/master/cinlist/forms.py)
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Refer:**
[Working with forms - Django](https://docs.djangoproject.com/en/4.1/topics/forms/#more-on-fields)

**Example:**
```python
class SignUpForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'mt-3 input w-75 p-3',
            'placeholder': 'Name'
        }),
    )
...
...
```

**Comment by heraldjose10** [comment]
I would like to take this up. Please assign this to me

**Comment by akshayitzme** [comment]
> I would like to take this up. Please assign this to me

sure :+1:  go ahead !

**Comment by heraldjose10** [comment]
Completed. Please take a look at PR #34
