### ISSUE TITLE
py: define attributes for the email field

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#31]
we have to style the email field in the SignUpForm located in [forms.py](https://github.com/akshayitzme/cinlist/blob/master/cinlist/forms.py)

- we can achieve this by adding needed classes and placeholder value in the attrs of the widget variable of the email field.
- Target File: [forms.py](https://github.com/akshayitzme/cinlist-django/blob/master/cinlist/forms.py)
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Refer:**
[Working with forms - Django](https://docs.djangoproject.com/en/4.1/topics/forms/#more-on-fields)

**Example:**
```python
class SignUpForm(UserCreationForm):
  ...
    email = forms.EmailField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'mt-3 input w-75 p-3',
                'type': 'email',
                'placeholder': 'Email'
            }),
    )
  ...

```

**Comment by ogdhruv** [comment]
I would like to work on it, please assign this issue to me.

**Comment by ogdhruv** [comment]
Aren't #32 and #33 also related to this same issue, I think these all problems should be considered as one.

**Comment by akshayitzme** [comment]
> Aren't #32 and #33 also related to this same issue, I think these all problems should be considered as one.

@ogdhruv Yes you're right. But since this repo is a part of Hacktoberfest event. I'm trying to produce more issues to help the newcommers.

**Comment by ogdhruv** [comment]
okay that is understandable, please assign all three to me (#32, #33 also)

**Comment by akshayitzme** [comment]
> okay that is understandable, please assign all three to me (#32, #33 also). I am also in hacktoberfest

i can do that but first please send a message in those issues. then only i can assign someone from the conversation.

**Comment by ogdhruv** [comment]
assign me this issue also

**Comment by ogdhruv** [comment]
Opened a PR #45  @akshayitzme
Please take a look.
Let me know if any changes are needed.

**Comment by ogdhruv** [comment]
if this is resolved please close this issue.
