### ISSUE TITLE
py: define attributes for the password1 field

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#32]
we have to style the password1 field in the SignUpForm located in [forms.py](https://github.com/akshayitzme/cinlist/blob/master/cinlist/forms.py)

- we can achieve this by adding needed classes and placeholder value in the attrs of the widget variable of the password1 field.
- Target File: [forms.py](https://github.com/akshayitzme/cinlist-django/blob/master/cinlist/forms.py)
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Refer:**
[Working with forms - Django](https://docs.djangoproject.com/en/4.1/topics/forms/#more-on-fields)

**Example:**
```python
class SignUpForm(UserCreationForm):
  ...
   password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'mt-3 input w-75 p-3',
            'placeholder': 'Password'
        }),
    )
  ...

```

**Comment by ogdhruv** [comment]
please assign this issue to me.

**Comment by ogdhruv** [comment]
Opened a PR #46    @akshayitzme
Please take a look.
Let me know if any changes are needed.
