### ISSUE TITLE
py: define attributes for the password2 field

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#33]
we have to style the password2 field in the SignUpForm located in [forms.py](https://github.com/akshayitzme/cinlist/blob/master/cinlist/forms.py)

- we can achieve this by adding needed classes and placeholder value in the attrs of the widget variable of the password2 field.
- Target File: [forms.py](https://github.com/akshayitzme/cinlist-django/blob/master/cinlist/forms.py)
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Refer:**
[Working with forms - Django](https://docs.djangoproject.com/en/4.1/topics/forms/#more-on-fields)

**Example:**
```python
class SignUpForm(UserCreationForm):
  ...
   password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'mt-3 input w-75 p-3',
            'placeholder': 'Confirm Password'
        }),
    )
  ...

```

**Comment by ogdhruv** [comment]
please assign this issue to me
