### ISSUE TITLE
html: change title of index page

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#37]
we havent set a title of the index page. a block for title is defined in the base template [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html)

- edit [index.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/index.html) and set appropriate title

**Example**
- title: `Cinlist &mdash; List your favorite movies, series, shows and more`
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Comment by MQ-xz** [comment]
Hey, am Interested to take up this issue!

**Comment by MQ-xz** [comment]
Hey, it's updated the check pr #40  .
