### ISSUE TITLE
html: change title of signup page

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#38]
we havent set a title of the signup page. a block for title is defined in the base template [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html)

- edit [signup.html](https://github.com/akshayitzme/cinlist-django/blob/master/cinlist/templates/signup.html) and set appropriate title

**Example**
- title: `Sign Up &mdash; Cinlist`
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Comment by MQ-xz** [comment]
Hi, I'm Interested to take up this issue!

**Comment by MQ-xz** [comment]
Hey, it done Check #41 .
