### ISSUE TITLE
html: change title of signin page

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#39]
we havent set a title for the signin page. a block for title is defined in the base template [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html)

- edit [signin.html](https://github.com/akshayitzme/cinlist-django/blob/master/cinlist/templates/signin.html) and set appropriate title

**Example**
- title: `Sign In &mdash; Cinlist`
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

**Comment by MQ-xz** [comment]
Hi, I'm Interested to take up this issue!

**Comment by MQ-xz** [comment]
Hey, its Updated check pr #43
