### ISSUE TITLE
html: dynamic title

### ISSUE THREAD

**Issue by akshayitzme** [akshayitzme/cinlist#8]
In further development of the application, we will be needing to set different titles to each pages. to set that easily, we can make use of Django's templating. 

- define a block inside the title tag, defined in  [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html)
- ✨ Feel free to add your own changes ! 
- 💬 drop a comment if you like to take up this issue, so i can assign it to you.

### Refer:
[Django block Template Tag](https://www.w3schools.com/django/ref_tags_block.php)
### Example:
```html
<title>{% block title %}{% endblock %}</title>
```

**Comment by Marsh-sudo** [comment]
Assign me this but first kindly explain the issue you want to solve kindly

**Comment by akshayitzme** [comment]
> Assign me this but first kindly explain the issue you want to solve kindly

We have a base template file  [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html).
In future, to add more pages to the app, we will be extending this layout to not repeat the boilerplate html. such as bootstrap includes and the base tags like html, head, body etc. 

If you examine the [main.html](https://github.com/akshayitzme/cinlist/blob/master/cinlist/templates/layouts/main.html) file, we can see there is a predefined title,

```html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>Document</title>   ------> Here
</head>

<body>

</body>

</html>
```

please refer the example and understand what needs to be changed.

**If you still have doubts feel free to ask**
